apiVersion: apps/v1
kind: Deployment

metadata:
  name: metrics-server
  namespace: data-pipelines

spec:
  replicas: 1

  selector:
    matchLabels:
      app: metrics-server

  template:
    metadata:
      labels:
        app: metrics-server

    spec:
      containers:
        - name: metrics-server

          image: localhost:5000/weather-etl:metrics-v2

          imagePullPolicy: IfNotPresent

          command:
            - python
            - -m
            - src.metrics_server

          ports:
            - containerPort: 8000