apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "weather-etl.labels" . | nindent 4 }}

spec:
  replicas: 1

  selector:
    matchLabels:
      {{- include "weather-etl.postgresLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "weather-etl.postgresLabels" . | nindent 8 }}

    spec:
      containers:
        - name: postgres

          image: {{ .Values.postgres.image }}

          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}

          ports:
            - containerPort: 5432

          envFrom:
            - configMapRef:
                name: postgres-config

          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.username }}
                - -d
                - {{ .Values.postgres.database }}

            initialDelaySeconds: 10
            periodSeconds: 5

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-init-schema
              mountPath: /docker-entrypoint-initdb.d/schema.sql
              subPath: schema.sql

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-init-schema
          configMap:
            name: postgres-init-schema